/* eslint-disable no-process-env */
import { defineConfig } from "prisma/config";

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx ./prisma/seed.ts",
  },
  datasource: {
    url: process.env.DIRECT_URL, // Direct database URL for migrations
  },
});
