import { defineConfig, env } from "prisma/config";

import processEnv from "./server/lib/env";

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx ./prisma/seed.ts",
  },
  datasource: {
    url: processEnv.NODE_ENV === "development" ? env("DATABASE_URL") : env("DIRECT_URL"), // Direct database URL for migrations
  },
});
