name: Project lint & type-check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm ci
      - name: Linting 
        run: npm run lint
      - run: npm run typecheck
